language: node_js
node_js: node

branches:
  only:
    - gh-pages

install: npm install -g gitbook-cli

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./generate-html.sh; fi'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./open-pr.sh; fi'
